### ISSUE TITLE
Dealing with unsoundness in chrono

### ISSUE THREAD

**Issue by djc** [est31/rcgen#65] opened 2021-10-25 09:25 UTC
Hey, have you decided what you want to do with the chrono issues?

https://rustsec.org/advisories/RUSTSEC-2020-0159

Maybe it makes sense for rcgen to just adopt time 0.3 instead?

**Comment by makr11st** [comment] 2021-12-08 13:32
@est31 Hi, is there an update on #66 it seems the PRs in deps are now merged.

**Comment by est31** [comment] 2021-12-08 23:27
The time crate does not support leap seconds, see https://github.com/time-rs/time/issues/193 . This can be an issue for certificate generation libraries as single seconds [can become important](https://community.letsencrypt.org/t/2021-06-08-certificate-lifetime-incident-valid-for-an-extra-one-second/153426) in the security domain. So I'm a bit reluctant, because rcgen does not use the offending function that makes chrono unsafe in the database, but it does rely on leap second support. The PR #66 has to change some of the unit tests that check for leap seconds.

Ultimately, if there is no movement on the time crate, I think I'll just merge it as is and accept the regression.

**Comment by est31** [comment] 2021-12-09 01:29
Alright, when the new ring version will be released, I'll switch to time: https://github.com/briansmith/ring/issues/1416#issuecomment-989381344

**Comment by makr11st** [comment] 2021-12-09 09:34
No worries and no pushing, just was wondering if there were additional dependencies you were waiting for, it makes sense to implement proper leap seconds handling. I saw the leap second discussion in the other repos, but it doesn't seem like a straightforward problem to solve.
Thanks for replying.

**Comment by est31** [comment] 2022-01-13 15:28
Hmmm no changes for ring. There seems to be progress on the chrono front though: https://github.com/chronotope/chrono/pull/632#issuecomment-1002788352

**Comment by est31** [comment] 2022-01-13 15:30
Also: https://github.com/chronotope/chrono/pull/639

**Closed** 2022-02-02 18:23 UTC

**Comment by makr11st** [comment] 2022-02-10 00:32
Thanks for the merge and release.
