### ISSUE TITLE
Certificate imported via from_ca_cert_* serializes incorrectly

### ISSUE THREAD

**Issue by jean-airoldie** [est31/rcgen#40] opened 2020-09-19 23:29 UTC
Importing a `Certificate` via `from_ca_cert_pem` or `from_ca_cert_der` then running `Certificate::serialize_der` on it yields invalid certificates, at least according to webpki (BadDer).

My work around was to keep a copy of the imported certificate as a backup and yield that backup when the certificate is requested.

**Comment by est31** [comment] 2020-09-20 02:14
@jean-airoldie can you give have example certs? Best both the one imported and the one that rcgen exports.

**Comment by jean-airoldie** [comment] 2020-09-20 02:21
I used a CA certificate generated by rcgen then serialized & imported it.

**Comment by est31** [comment] 2020-09-20 02:32
The PEM ascii based representation would be optimal. That way I'd know what goes wrong. `BadDer` could be basically anything.

**Comment by jean-airoldie** [comment] 2020-09-20 02:40
This is a newly generated CA certificate PEM:
```
-----BEGIN CERTIFICATE-----                                                                                                                                                                                        
MIIBozCCAUigAwIBAgIBKjAKBggqhkjOPQQDAjAuMRIwEAYDVQQDDAlNYXN0ZXIg
Q0ExGDAWBgNVBAoMD0NyYWIgd2lkZ2l0cyBTRTAgFw03NTAxMDEwMDAwMDBaGA80          
MDk2MDEwMTAwMDAwMFowLjESMBAGA1UEAwwJTWFzdGVyIENBMRgwFgYDVQQKDA9D
cmFiIHdpZGdpdHMgU0UwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATadCZDXl2I                                                                                                                                                   
IqKVQ1kxpdTz0fyMfwJL5vnYHDk06PhDH7xU8jFpvFLloiilPUB3kZ/2gFqANyL9
I1EUMhCeKr4Zo1UwUzAhBgNVHREEGjAYggtjcmFicy5jcmFic4IJbG9jYWxob3N0
MB0GA1UdDgQWBBR/oQTzfXKpr3ZyDNj9/7ekIvyIBzAPBgNVHRMBAf8EBTADAQH/
MAoGCCqGSM49BAMCA0kAMEYCIQDM5UvVVDW/NiL46p1M0nJ98aynO3IL37F4aH0u
6XN/vQIhAPMEBVOZJNR7GgLtfDNNnnh9BJOQmlfgsNmr9aehjbxA 
-----END CERTIFICATE-----
```

...and this is the same CA serialized & imported:
```
-----BEGIN CERTIFICATE-----
MIIBSzCB8aADAgECAgEqMAoGCCqGSM49BAMCMC4xEjAQBgNVBAMMCU1hc3RlciBD
QTEYMBYGA1UECgwPQ3JhYiB3aWRnaXRzIFNFMCAXDTc1MDEwMTAwMDAwMFoYDzQw
OTYwMTAxMDAwMDAwWjAuMRIwEAYDVQQDDAlNYXN0ZXIgQ0ExGDAWBgNVBAoMD0Ny
YWIgd2lkZ2l0cyBTRTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABNp0JkNeXYgi
opVDWTGl1PPR/Ix/Akvm+dgcOTTo+EMfvFTyMWm8UuWiKKU9QHeRn/aAWoA3Iv0j
URQyEJ4qvhkwCgYIKoZIzj0EAwIDSQAwRgIhAI0JxIZGYA+2IYBVgf7on9DqdCgP
AbQ/+cF4A35YsZGfAiEA7Pe1OlmkdNacBicdZGZ/tKHzxcw9VQQsVgq2yshkaF8=
-----END CERTIFICATE-----
```

**Comment by est31** [comment] 2020-09-20 02:41
To make sure: you use the 0.8.5 version of rcgen? There were BadDer bugs in the past that were fixed, but this might be a new one.

**Comment by jean-airoldie** [comment] 2020-09-20 02:43
Yep.

**Comment by est31** [comment] 2020-09-20 02:44
Hmm the two certificates are the same, except that the exported cert lacks extensions. That's not good...

**Comment by est31** [comment] 2020-09-20 02:44
Thanks for the report, will take a look at a fix later.

**Comment by est31** [comment] 2020-09-20 04:37
Yeah so the issue is that the `from_ca_cert_*` functions are really only meant for importing certificates meant for signing. Exporting those certificates is not supported. That's what the docs say as well.

Thus this is less a bug and more a feature request: loading `CertificateParams` from their serialized certificate form, allowing for edits. I think it would be better to offer separate functions for that, as currently, if one of the `from_ca_cert_*` functions are fed e.g. serial numbers larger than 64 bits, it won't yield an error. A function that parses those serial numbers though would have to yield errors.

**Comment by est31** [comment] 2020-09-20 04:46
Also note that in general, it's better to not keep a `Certificate` around and then call `serialize_der` and `serialize_pem` on it on each request or so, because that invokes the entire serialization code again and again, and also repeats signatures. Some of the signature algorithms supported by rcgen depend on random elements, so the generated results might be different between calls. It's best to keep them around in serialized form :).

**Comment by jean-airoldie** [comment] 2020-09-20 05:40
Cool. I'll cache the serialized certificate then.

**Comment by est31** [comment] 2020-11-09 02:47
Closing as per ea0006031a7ffdbf4c68a1af158e056f292da8e5

**Closed by est31** 2020-11-09 02:47 UTC
Labels: enhancement
